# Generated by Django 3.2.8 on 2021-10-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('GameId', models.AutoField(primary_key=True, serialize=False)),
                ('HomeTeam', models.CharField(max_length=100)),
                ('VisitorTeam', models.CharField(max_length=100)),
            ],
        ),
    ]
